### ISSUE TITLE
Variables in use of the ansible-pull-script.sh are not defined in defaults in fgci-install

### ISSUE THREAD

**Issue by martbhell** [CSCfi/ansible-role-fgci-install#1]
This template:

https://github.com/CSC-IT-Center-for-Science/ansible-role-fgci-install/blob/master/templates/ansible-pull-script.sh.j2

Is using variables that are not defined in defaults/main.yml

This should be fixed or the role should be made dependent on a role which _does_ contain these variables in defaults.yml

**Comment by A1ve5** [comment]
Proposed changes applied: c9c89a163822b83eac4f91e8fe4c890aae050118
