### ISSUE TITLE
Can we stop using pull_variables.yml?

### ISSUE THREAD

**Issue by martbhell** [CSCfi/ansible-role-fgci-install#14]
The fgci-install role rsyncs group_vars (and host_vars if these are defined) to the install node's www directory.
The ansible-pull-script.sh on the compute nodes downloads all these.

The fgci-install role also templates in a pull_variables.yml to the install node which the ansible-pull-script.sh cronjob also fetches. 

The pull_variables.yml might not be needed anymore. 

Before it can be removed all the variables that are defined in it needs to be moved to:
- the examples/ 
- every site's group_vars/ 
- synced to every site's the install node.

**Comment by A1ve5** [comment]
this file isn't being properly populated either:

## [root@io3 ~]# cat pull_variables.yml 

# variables for ansible-pull

# 

#
pull_install_ip: "10.1.1.2"
pull_login_ip: "10.1.1.4"
running_as_ansible_pull: True

ntp_config_server: [ "{{ pull_install_ip }}", "10.1.1.1" ]
collectd_network_server_host: "{{ pull_install_ip }}" 
adminMailAddr: "fgci-csc-admins@listat.csc.fi"
slurm_service_node: "io-install"
slurm_munge_key_from_nfs: True

What are the consequences?

**Comment by martbhell** [comment]
The "slurm_munge_key_from_nfs: True" sets the nodes to fetch the munge.key from NFS when using ansible-pull. For ansible pull to continue to work after removing the pull_variables.yml we need to change this to True.

**Comment by martbhell** [comment]
The running_as_ansible_pull we are now using with the ansible-role-cuda ( to not wait_for a handler for the machine to come back when running ansible-pull ). 
Because of that it looks like we have to keep using pull_variables.yml.
Closing this issue. 
If in the future there is a variable in ansible_facts that shows if we are in pull mode or not we could re-open this. Or if we get rid of the handler in the cuda role.
