### ISSUE TITLE
randomize  /usr/local/bin/ansible-pull-script.sh runs

### ISSUE THREAD

**Issue by A1ve5** [CSCfi/ansible-role-fgci-install#18]
Would it also make sense to randomize 
/usr/local/bin/ansible-pull-script.sh runs, so that on different nodes 
ansible-pull-script.sh would run at different time? Or is it implemented 
already? On Triton they all like this

pdsh -f 500 -a cat /etc/cron.d/ansible-pull
...
wsm34: */120 \* \* \* \* root /bin/bash 
/usr/local/bin/ansible-pull-script.sh >/var/log/ansible.log 2>&1
...

Random runs would be a workaround for proxy and 
http://install/group_vars/ sessions as well, to avoid overhelming of 
hundreds of connections at once.

Analyzes of /var/log/ansible.log shows that often connections are 
dropped due to timelimits.

Another option would skip cron runs on compute nodes and do it through 
playbook from admin. This is easily scriptable, like for instance a 
portion of 32 nodes every 15 minutes or something similar. Bur random 
still would be more intelligent.

Requester: Ivan Degtyarenko from Aalto Univ. by e-Mail

**Comment by martbhell** [comment]
Have you tried to increase {{ ansible_pull_sleep }} ?

Increasing that number makes the nodes sleep for a wider and longer amount of time - in my mind reducing the number of nodes running ansible-pull at the same time. 

<pre>
time=$[ ( $RANDOM % {{ ansible_pull_sleep }} )  + 1 ]
/bin/sleep "$time"s
</pre>

https://github.com/CSC-IT-Center-for-Science/ansible-role-fgci-install/blob/master/templates/ansible-pull-script.sh.j2

**Comment by jabl** [comment]
Bumped to 1800s. Hopefully it'll help.

**Comment by martbhell** [comment]
For reference, what was it set to before? If this helps we can write a recommendation what it should be in regards to number of nodes. Or maybe even increase it for larger clusters with some ansible magic.

**Comment by jabl** [comment]
It was 10s (copied from fgci-ansible:/examples/group_vars/all/all.example). Maybe 1800s is a bit excessive, but certainly 10s is too small to be meaningful. Maybe 600s is a good default?

**Comment by martbhell** [comment]
Maximum time it can be is {{ ansible_pull_cron_minute_interval }} - $time_ansible_pull_takes, 30 minutes max for a fresh node maybe (at least the GPU nodes takes quite some time to do)? 90*60=5400s

I've increase default longest sleep to 600s in https://github.com/CSC-IT-Center-for-Science/fgci-ansible/commit/0c04db8724a17d0d349db6eeac40e75b911a16a2 but not the default in fgci-install role (which is 30s).
