### ISSUE TITLE
Make random_wait ansible-pull-script.sh use

### ISSUE THREAD

**Issue by martbhell** [CSCfi/ansible-role-fgci-install#2]
ansible_pull_sleep is a variable defined in 
https://github.com/CSC-IT-Center-for-Science/fgci-ansible/blob/master/examples/group_vars/all/all.example#L141

This one could be used (as well as the other variables).
Some updates have been lost for the ansible-pull-script.sh

**Comment by A1ve5** [comment]
here: https://github.com/CSC-IT-Center-for-Science/ansible-role-fgci-install/commit/a7d4ea655a78c77bb9bc4834b4e71a240fe77a31

**Comment by martbhell** [comment]
There's three more places in that same file where sleep interval is hard-coded:

https://github.com/CSC-IT-Center-for-Science/ansible-role-fgci-install/blob/a7d4ea655a78c77bb9bc4834b4e71a240fe77a31/templates/ansible-pull-script.sh.j2#L40

and these two:
https://github.com/CSC-IT-Center-for-Science/ansible-role-fgci-install/blob/a7d4ea655a78c77bb9bc4834b4e71a240fe77a31/templates/ansible-pull-script.sh.j2#L55-L56

**Comment by A1ve5** [comment]
ah, yes. fixing it. thanks.
