### ISSUE TITLE
$runtime does not take into account ntp updates

### ISSUE THREAD

**Issue by martbhell** [CSCfi/ansible-role-fgci-install#28]
[1](https://github.com/CSC-IT-Center-for-Science/ansible-role-fgci-install/commit/645f34221c079633d184af6b1d35e71287a2dde9) This change does not take into account that the time on the system is likely out of date before ansible runs the first time. We have seen $runtimes > 5000 seconds. 

The script should use something other than "date". Some suggestions:
- export TIMEFORMAT=%E; time sleep 1
- /bin/time --format=%e sleep 1
- times and change format somehow?
- echo $SECONDS 

It could also:
- not send the time if the time is not in sync (ntpdate -d some_ntp_server_in_ntp.conf)
- not send it if it's negative (but that doesn't catch where the time is adjusted the other way resulting in an abnormally long runtime)

**Comment by martbhell** [comment]
Added a commit in there. Our test system's compute nodes appear to have pretty good system time so I can't test this there. Based on ansible-pull-dashboard in grafana some nodes in triton get their time changed with 80 minutes sometimes.

Would you be able to test this update to the ansible-pull-script for me @jabl ? I could also put it in fgci-ansible devel branch already and we can see how it goes.

**Comment by martbhell** [comment]
Unfortunately $SECONDS have the same issue as the date command. No need for more testing right now.

Doing an 

<pre>export SECONDS=""
</pre>

resets the timer to zero and $SECONDS starts increasing again.

<pre>
[root@me ~ ]$ date
Tue Sep 13 08:07:32 EEST 2016
[root@me ~ ]$ echo $SECONDS
22
[root@me ~ ]$ echo $SECONDS
23
[root@me ~ ]$ echo $SECONDS
24
[root@me ~ ]$ date -s "2016-09-13 08:00:00"
Tue Sep 13 08:00:00 EEST 2016
[root@me ~ ]$ date
Tue Sep 13 08:00:01 EEST 2016
[root@me ~ ]$ echo $SECONDS
-429
</pre>

**Comment by jabl** [comment]
The command

awk '/^now/ {print $3; exit}' /proc/timer_list

should provide a monotonic clock, nanoseconds since boot.

**Comment by martbhell** [comment]
Very nice, thank you. That seems to work nicely around this issue.

**Comment by martbhell** [comment]
https://github.com/CSC-IT-Center-for-Science/fgci-ansible/commit/e869493ed61eb49cf48caa5887fd888ab5f34dc8 fixes this.
