### ISSUE TITLE
ansible-pull-script.sh - ifup ib0 improvements

### ISSUE THREAD

**Issue by martbhell** [CSCfi/ansible-role-fgci-install#3]
The script has a:

<pre>
 # Bring Up Ib0
 /usr/sbin/ifup ib0
</pre>

Which outputs this if the interface is already up:

<pre>
# /usr/sbin/ifup ib0
RTNETLINK answers: File exists
</pre>

We could check if ib0 is up before running ifup.

"ip link ib0 show|grep DOWN|wc -l" perhaps.

Would also be nice to make this part optional & the interface name a variable.

**Comment by martbhell** [comment]
That commit doesn't solve this issue, but it's a good improvement anyway :)

The error was when bringing an interface up which is already up.

**Comment by A1ve5** [comment]
Ah, didn't read everything. Let's put it back on the stack
