### ISSUE TITLE
Role broken by https://github.com/CSCfi/ansible-role-fgci-install/commit/a23a4cfb9b3f91fd0cebb43b78535c63af80194c

### ISSUE THREAD

**Issue by jabl** [CSCfi/ansible-role-fgci-install#43]
The commit https://github.com/CSCfi/ansible-role-fgci-install/commit/a23a4cfb9b3f91fd0cebb43b78535c63af80194c breaks the role:

<pre><code>
fatal: [NODENAME_RETRACTED]: FAILED! => {"reason": "Syntax Error while loading YAML.\n  mapping values are not allowed in this context\n\nThe error appears to be in '/some/path/fgci-ansible/roles/ansible-role-fgci-install/tasks/service.yml': line 113, column 12, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  yum: name=PyYAML\n           ^ here\n\nThere appears to be both 'k=v' shorthand syntax and YAML in this task. Only one syntax may be used.\n"}
</code></pre>

**Comment by VilleS1** [comment]
Ok, good that you noticed. Merged the patch
