### ISSUE TITLE
Improve proxy usage in ansible-pull-script.sh

### ISSUE THREAD

**Issue by martbhell** [CSCfi/ansible-role-fgci-install#6]
```
--2016-03-02 09:45:50--  http://2/
Connecting to 10.1.1.4:3128... connected.
Proxy request sent, awaiting response... 503 Service Unavailable
2016-03-02 09:45:50 ERROR 503: Service Unavailable.

```

This appears to be from the wget of the group_vars

https://github.com/CSC-IT-Center-for-Science/ansible-role-fgci-install/blob/master/templates/ansible-pull-script.sh.j2#L58

**Comment by A1ve5** [comment]
Not breaking anything. We'll work on it on future releases

**Comment by martbhell** [comment]
As all commands connect to the internal IP of the install node we can remove all the proxy environment variables.

**Comment by martbhell** [comment]
I don't think we should remove the proxy environment variables _yet_ because roles are fetching files from remote sources and there the proxy can still help.
If we could setup mirrors of all the remote files in all the playbooks, then we could remove the environment variables. This would mean adding to all the roles that the remote file is a variable so we could change where to fetch it from. Quite a bit of work, but primary benefit is that it would make each cluster independent of github and internet connectivity.

**Comment by A1ve5** [comment]
thing this is now solved by gitmirror
